language: node_js
node_js:
- '4.0'
- '0.12'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g gulp
- npm install -g typings
- npm install
script: gulp buildtest
